In [20]:
import sdv
import faker
import pandas
import numpy
import random

In [ ]:
{
	"eventId": "244ca386-89a5-4b7e-8ac4-4b7dd4fee74e",
	"eventTimestamp": "11/12/2022 08:20:43",
	"dataSource": "app",
	"healthState": "good",
	"generalHealthStats": {
		"stepCount(cumulativeforday)": 4000,
		"stress(0to5)": 3,
		"bloodOxygen(mmHg)": 95,
		"sleepHours": 8,
		"REMsleepHours": 4,
		"caloriesBurnt(cumulativeforday)": 2000
	},
	"user": {
		"user_id": "fdde5bd5-1146-48df-94ef-d56532290901",
		"firstname": "john",
		"lastname": "doe",
		"gender": "male",
		"age": 23,
		"weight(kg)": 88,
		"height(cm)": 176
	},
	"vitals": {
		"heartRate(bpm)": 72,
		"systolicBloodPressure(mmHg)": 130,
		"diastolicBloodPressure(mmHg)": 70,
		"bodyTemperature(F)": 98.6,
		"breathingFrequency(perminute)": 15
	}
}

In [29]:
import secrets
secrets.randbelow(10)

5

In [74]:
import uuid
from random import randrange
from datetime import timedelta, datetime

def fetch_random_date(start, end):
    """
    This function will return a random datetime between two datetime 
    objects.
    """
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return start + timedelta(seconds=random_second)

random.seed(8)
fake.seed_instance(8)

event_data = {}

for idx in range(10_000):
    event = {}
    
    event_id = str(uuid.uuid4())
    event['eventId'] = event_id
    
    start_date = datetime(2022, 8, 1)
    end_date = datetime(2022, 12, 31)
    event['eventTimestamp'] = fetch_random_date(start_date, end_date)
    
    random_no = secrets.randbelow(2)
    source = 'app' if random_no == 1 else 'manual'
    event['dataSource'] = source
    
    # TODO: FIX
    random_no = secrets.randbelow(2)
    state = 'good' if random_no == 1 else 'bad'
    event['healthState'] = state
    
    generalHealthStats = {}
    
    stepCount = secrets.randbelow(30000)
    generalHealthStats['stepCount(cumulativeforday)'] = stepCount
    
    bloodOxygenAvg = 90 + secrets.randbelow(10)
    generalHealthStats['bloodOxygenAvg(mmHg)'] = bloodOxygenAvg
    
    stress = secrets.randbelow(5)
    generalHealthStats['stress(0to5)'] = stress
    
    sleepHours = 4 + secrets.randbelow(4)
    generalHealthStats['sleepHours'] = sleepHours
    
    REMsleepHours = secrets.randbelow(4)
    generalHealthStats['REMsleepHours'] = REMsleepHours
    
    caloriesBurnt = 1800 + secrets.randbelow(600)
    generalHealthStats['caloriesBurnt(cumulativeforday)'] = caloriesBurnt
    
    event['generalHealthStats'] = generalHealthStats
    
    user = {}
    
    user['user_id'] = str(uuid.uuid4())
    
    name = fake.name()
    user['firstname'] = name.split(' ')[0]
    user['lastname'] = name.split(' ')[1]
    
    random_no = secrets.randbelow(2)
    gender = 'male' if random_no == 1 else 'female'
    user['gender'] = gender
    
    age = secrets.randbelow(60)
    user['age'] = age
    
    if age < 5:
        weight = secrets.randbelow(10)
        height = 10 + secrets.randbelow(40)
    elif 5 <= age <= 15:
        weight = 20 + secrets.randbelow(20)
        height = 50 + secrets.randbelow(80)
    elif age > 15:
        weight = 40 + secrets.randbelow(50)
        height = 140 + secrets.randbelow(60)
        
    user['weight(kg)'] = weight
    user['height(cm)'] = height
    
    event['user'] = user
    
    vitals = {}
    
    heartRate = 50 + secrets.randbelow(50)
    vitals['heartRate(bpm)'] = heartRate
    
    systolicBloodPressure = 50 + secrets.randbelow(40)
    vitals['systolicBloodPressure(mmHg)'] = systolicBloodPressure
    
    diastolicBloodPressure = 100 + secrets.randbelow(40)
    vitals['diastolicBloodPressure(mmHg)'] = diastolicBloodPressure
    
    bodyTemperature = 98 + secrets.randbelow(3)
    vitals['bodyTemperature(F)'] = bodyTemperature
    
    breathingFrequency = 10 + secrets.randbelow(12)
    vitals['breathingFrequency(perminute)'] = breathingFrequency
    
    event['vitals'] = vitals
    
    event_data[f'{event_id}'] = event

In [75]:
event_data = pd.DataFrame(event_data).T.reset_index(drop=True)
event_data = pd.concat([event_data, event_data['generalHealthStats'].apply(lambda x: pd.Series(x)), event_data['user'].apply(lambda x: pd.Series(x)), event_data['vitals'].apply(lambda x: pd.Series(x))], axis=1)

In [76]:
event_data.head()

,eventId,eventTimestamp,dataSource,healthState,generalHealthStats,user,vitals,stepCount(cumulativeforday),bloodOxygenAvg(mmHg),stress(0to5),...,lastname,gender,age,weight(kg),height(cm),heartRate(bpm),systolicBloodPressure(mmHg),diastolicBloodPressure(mmHg),bodyTemperature(F),breathingFrequency(perminute)
0,0383a7e7-807a-4dd1-9cc6-e5fee9fc1b10,2022-09-14 00:31:33,manual,good,"{'stepCount(cumulativeforday)': 8151, 'bloodOx...",{'user_id': 'd96c2414-cbfa-462e-9851-c2163242c...,"{'heartRate(bpm)': 71, 'systolicBloodPressure(...",8151,98,0,...,Martinez,female,25,51,190,71,86,121,98,15
1,7adc9f1a-bbae-41b5-a458-619784f76589,2022-10-11 22:14:39,manual,good,"{'stepCount(cumulativeforday)': 21112, 'bloodO...",{'user_id': '0e2975b0-c8f5-47f5-870b-91e31b667...,"{'heartRate(bpm)': 82, 'systolicBloodPressure(...",21112,90,0,...,Wright,male,15,33,112,82,58,126,100,18
2,13777fca-fe90-4d9e-84d1-572167023b49,2022-10-12 21:20:54,manual,bad,"{'stepCount(cumulativeforday)': 2745, 'bloodOx...",{'user_id': '83e13045-de5a-471f-8a07-84dcca9ca...,"{'heartRate(bpm)': 69, 'systolicBloodPressure(...",2745,93,4,...,Maria,male,35,45,190,69,80,106,100,10
3,d36a5d0c-616e-4da7-a5ce-8747c5733b55,2022-08-25 12:44:40,app,bad,"{'stepCount(cumulativeforday)': 4882, 'bloodOx...",{'user_id': '37f86216-dfe2-4796-bcb0-b05a01346...,"{'heartRate(bpm)': 86, 'systolicBloodPressure(...",4882,96,4,...,Rivas,female,15,37,108,86,53,115,99,13
4,74792c48-0939-4e77-aaa9-8bbe3ed1c08c,2022-09-07 11:59:19,manual,bad,"{'stepCount(cumulativeforday)': 10145, 'bloodO...",{'user_id': '7ffe75be-1e87-4c77-a692-c64f5c195...,"{'heartRate(bpm)': 85, 'systolicBloodPressure(...",10145,95,1,...,Adams,male,51,44,162,85,84,129,100,21

In [77]:
event_data.to_csv('data_dump.csv')

In [79]:
event_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   eventId                          10000 non-null  object
 1   eventTimestamp                   10000 non-null  datetime64[ns]
 2   dataSource                       10000 non-null  object
 3   healthState                      10000 non-null  object
 4   generalHealthStats               10000 non-null  object
 5   user                             10000 non-null  object
 6   vitals                           10000 non-null  object
 7   stepCount(cumulativeforday)      10000 non-null  int64
 8   bloodOxygenAvg(mmHg)             10000 non-null  int64
 9   stress(0to5)                     10000 non-null  int64
 10  sleepHours                       10000 non-null  int64
 11  REMsleepHours                    10000 non-null  int64
 12  caloriesBurnt(cumulativeforday)  10000 non-null  int64
 13  user_id                          10000 non-null  object
 14  firstname                        10000 non-null  object
 15  lastname                         10000 non-null  object
 16  gender                           10000 non-null  object
 17  age                              10000 non-null  int64
 18  weight(kg)                       10000 non-null  int64
 19  height(cm)                       10000 non-null  int64
 20  heartRate(bpm)                   10000 non-null  int64
 21  systolicBloodPressure(mmHg)      10000 non-null  int64
 22  diastolicBloodPressure(mmHg)     10000 non-null  int64
 23  bodyTemperature(F)               10000 non-null  int64
 24  breathingFrequency(perminute)    10000 non-null  int64
dtypes: datetime64[ns](1), int64(14), object(10)
memory usage: 1.9+ MB

In [18]:
# 1
# from random import randrange
# import datetime 


# def random_date(start,l):
#     current = start
#     while l >= 0:
#         current = current + datetime.timedelta(minutes=randrange(10))
#         yield current
#         l-=1

# startDate = datetime.datetime(2013, 9, 20,13, 0)

# for x in reversed(list(random_date(startDate,10))):
#     print x.strftime("%d/%m/%y %H:%M")

# 2
# def randomtimes(stime, etime, n):
#     frmt = '%d-%m-%Y %H:%M:%S'
#     stime = datetime.datetime.strptime(start, frmt)
#     etime = datetime.datetime.strptime(end, frmt)
#     td = etime - stime
#     return [random.random() * td + stime for _ in range(n)]

# 3
from random import randrange
from datetime import timedelta

def random_date(start, end):
    """
    This function will return a random datetime between two datetime 
    objects.
    """
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return start + timedelta(seconds=random_second)

from datetime import datetime

d1 = datetime(2020, 1, 1)
d2 = datetime(2020, 5, 1)

print(random_date(d1, d2))

2020-03-13 21:57:59

In [3]:
import uuid
str(uuid.uuid4())

'08975735-4faf-4722-ac60-fe2ede48f56b'

In [5]:
from faker import Faker
fake = Faker()

fake.name()

'David Haynes'

In [41]:
name = fake.name()
name.split(' ')[0], name.split(' ')[1]

('Sonya', 'Marquez')

In [ ]:
fake.gend

In [6]:
from sdv.demo import load_timeseries_demo

data = load_timeseries_demo()
data.head()

,Symbol,Date,Open,Close,Volume,MarketCap,Sector,Industry
0,AAPL,2018-12-31,39.632500,39.435001,140014000,7.378734e+11,Technology,Computer Manufacturing
1,AAPL,2019-01-02,38.722500,39.480000,148158800,7.378734e+11,Technology,Computer Manufacturing
2,AAPL,2019-01-03,35.994999,35.547501,365248800,7.378734e+11,Technology,Computer Manufacturing
3,AAPL,2019-01-04,36.132500,37.064999,234428400,7.378734e+11,Technology,Computer Manufacturing
4,AAPL,2019-01-07,37.174999,36.982498,219111200,7.378734e+11,Technology,Computer Manufacturing

In [7]:
data.shape

(25784, 8)

In [8]:
entity_columns = ['Symbol']
context_columns = ['MarketCap', 'Sector', 'Industry']
sequence_index = 'Date'

In [9]:
data = data[:100]

In [10]:
from sdv.timeseries import PAR

model = PAR(
    entity_columns=entity_columns,
    context_columns=context_columns,
    sequence_index=sequence_index,
)
model.fit(data)

# 1
# field_types = {
#     'Symbol': {
#         'type': 'id',
#         'subtype': 'string',
#         'regex': '[A-Z]{2,4}'
#     }
# }
# model = PAR(
#     entity_columns=entity_columns,
#     context_columns=context_columns,
#     sequence_index=sequence_index,
#     field_types=field_types
# )
# model.fit(data)

# 2
# model = PAR(
#     entity_columns=entity_columns,
#     sequence_index=sequence_index,
#     field_types=field_types,
# )
# model.fit(no_context)
# model.sample(num_sequences=1).head()

# 3 - probably most suitable
# model = PAR(
#     sequence_index=sequence_index,
# )
# model.fit(tsla)
# model.sample()

/usr/local/lib/python3.9/site-packages/deepecho/sequences.py:181: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for _, sequence in data.groupby(entity_columns):

In [11]:
new_data = model.sample(1)

In [12]:
new_data.head()

,Symbol,Date,Open,Close,Volume,MarketCap,Sector,Industry
0,a,2018-12-31,42.777598,46.809476,128188320,7.378734e+11,Technology,Computer Manufacturing
1,a,2019-01-01,42.157477,41.501273,145780437,7.378734e+11,Technology,Computer Manufacturing
2,a,2019-01-02,40.068821,39.633135,166649558,7.378734e+11,Technology,Computer Manufacturing
3,a,2019-01-03,39.179715,39.612503,170674496,7.378734e+11,Technology,Computer Manufacturing
4,a,2019-01-06,39.323123,38.352910,79697885,7.378734e+11,Technology,Computer Manufacturing

In [13]:
new_data.shape

(100, 8)

In [14]:
model.save('my_model.pkl')
loaded = PAR.load('my_model.pkl')
loaded.sample(num_sequences=1).head()

,Symbol,Date,Open,Close,Volume,MarketCap,Sector,Industry
0,a,2018-12-31,39.616091,44.780631,165510939,7.378734e+11,Technology,Computer Manufacturing
1,a,2019-01-02,38.996580,40.829762,213893240,7.378734e+11,Technology,Computer Manufacturing
2,a,2019-01-03,37.545285,39.784592,90801137,7.378734e+11,Technology,Computer Manufacturing
3,a,2019-01-04,38.112244,38.420026,190791591,7.378734e+11,Technology,Computer Manufacturing
4,a,2019-01-04,37.357364,37.892462,158769074,7.378734e+11,Technology,Computer Manufacturing

In [15]:
import pandas as pd

context = pd.DataFrame([
    {
        'Symbol': 'AAAA',
        'MarketCap': 1.2345e+11,
        'Sector': 'Technology',
        'Industry': 'Electronic Components'
    },
    {
        'Symbol': 'BBBB',
        'MarketCap': 4.5678e+10,
        'Sector': 'Health Care',
        'Industry': 'Medical/Nursing Services'
    },
])
context

  Symbol     MarketCap       Sector                  Industry
0   AAAA  1.234500e+11   Technology     Electronic Components
1   BBBB  4.567800e+10  Health Care  Medical/Nursing Services

In [16]:
new_data = model.sample(context=context)

KeyError: 'Electronic Components'

In [ ]:
new_data.shape